version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "
      cd backend &&
      uvicorn run:app
      --host 0.0.0.0 --port 8989
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload
      "
    volumes:
      - .:/opt
    ports:
      - "8989:8989"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod --quiet --logpath /dev/null

  nginx:
    image: nginx:latest
    ports:
      - 8181:8181
      - 27001:27001
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongodb
      - backend
      
 